on:
  schedule:
    - cron: '0 */3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_data_job:
    runs-on: ubuntu-latest
    name: Make sure data is current
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Data
        uses: ./.github/actions/update-data # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        id: index